version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - appnetwork

  web:
    build: api
    command: uvicorn api.app:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - appnetwork

volumes:
  pgdata:
networks:
  appnetwork: